export interface Program {
  id: string
  name: string
  code: string
  category: "cash-transfer" | "in-kind" | "education" | "healthcare" | "housing" | "emergency"
  status: "active" | "suspended" | "closed" | "pilot"
  description: string
  ministry: string
  budget: number
  disbursed: number
  beneficiaries: number
  targetBeneficiaries: number
  applicationsPending: number
  applicationsApproved: number
  applicationsRejected: number
  weight: number
  startDate: string
  endDate: string | null
  coverageAreas: string[]
  eligibilityCriteria: string[]
  deliveryRate: number
}

export interface Application {
  id: string
  applicantId: string
  applicantName: string
  programId: string
  programName: string
  status: "pending" | "under-review" | "approved" | "rejected" | "waitlisted"
  submittedDate: string
  lastUpdated: string
  priority: "low" | "medium" | "high" | "urgent"
  assignedOfficer: string | null
  division: string
  community: string
  requestedAmount: number | null
  approvedAmount: number | null
  notes: string[]
  documents: { name: string; status: "verified" | "pending" | "rejected" }[]
}

export const mockPrograms: Program[] = [
  {
    id: "prog-path",
    name: "Programme of Advancement Through Health and Education",
    code: "PATH",
    category: "cash-transfer",
    status: "active",
    description: "Conditional cash transfer program providing financial assistance to vulnerable households with children and elderly members.",
    ministry: "Ministry of Labour and Social Security",
    budget: 8500000000,
    disbursed: 6200000000,
    beneficiaries: 345000,
    targetBeneficiaries: 400000,
    applicationsPending: 2340,
    applicationsApproved: 12450,
    applicationsRejected: 1890,
    weight: 20,
    startDate: "2001-09-01",
    endDate: null,
    coverageAreas: ["Islandwide"],
    eligibilityCriteria: ["Income below poverty line", "Children 0-18 in household", "Elderly 60+ or disabled members"],
    deliveryRate: 94,
  },
  {
    id: "prog-housing",
    name: "Social Housing Programme",
    code: "SHP",
    category: "housing",
    status: "active",
    description: "Provides housing solutions and home improvement grants to low-income families and vulnerable populations.",
    ministry: "Ministry of Economic Growth and Job Creation",
    budget: 2500000000,
    disbursed: 1800000000,
    beneficiaries: 12500,
    targetBeneficiaries: 18000,
    applicationsPending: 3420,
    applicationsApproved: 4200,
    applicationsRejected: 2100,
    weight: 18,
    startDate: "2018-04-01",
    endDate: null,
    coverageAreas: ["Kingston", "St. Andrew", "St. Catherine", "Clarendon", "Manchester"],
    eligibilityCriteria: ["No current home ownership", "Income below $1.5M annually", "Jamaican citizen"],
    deliveryRate: 78,
  },
  {
    id: "prog-edu-grant",
    name: "Education Grant Programme",
    code: "EGP",
    category: "education",
    status: "active",
    description: "Financial support for students from low-income families to cover tuition, books, and school supplies.",
    ministry: "Ministry of Education and Youth",
    budget: 1200000000,
    disbursed: 980000000,
    beneficiaries: 89000,
    targetBeneficiaries: 100000,
    applicationsPending: 5600,
    applicationsApproved: 8900,
    applicationsRejected: 1200,
    weight: 16,
    startDate: "2015-01-01",
    endDate: null,
    coverageAreas: ["Islandwide"],
    eligibilityCriteria: ["Enrolled in approved institution", "Family income below threshold", "Satisfactory academic standing"],
    deliveryRate: 91,
  },
  {
    id: "prog-healthcare",
    name: "NHF Drug Subsidy Programme",
    code: "NHF-DSP",
    category: "healthcare",
    status: "active",
    description: "Subsidizes the cost of prescription drugs for chronic diseases including diabetes, hypertension, and asthma.",
    ministry: "Ministry of Health and Wellness",
    budget: 3200000000,
    disbursed: 2900000000,
    beneficiaries: 520000,
    targetBeneficiaries: 600000,
    applicationsPending: 1200,
    applicationsApproved: 18500,
    applicationsRejected: 450,
    weight: 15,
    startDate: "2003-07-01",
    endDate: null,
    coverageAreas: ["Islandwide"],
    eligibilityCriteria: ["Diagnosed with qualifying condition", "Valid NHF card", "Prescription from registered physician"],
    deliveryRate: 96,
  },
  {
    id: "prog-water-tank",
    name: "Rural Water Tank Programme",
    code: "RWTP",
    category: "in-kind",
    status: "active",
    description: "Provides water storage tanks to rural households without reliable access to piped water.",
    ministry: "Ministry of Local Government and Rural Development",
    budget: 450000000,
    disbursed: 320000000,
    beneficiaries: 8500,
    targetBeneficiaries: 12000,
    applicationsPending: 890,
    applicationsApproved: 2100,
    applicationsRejected: 340,
    weight: 12,
    startDate: "2019-06-01",
    endDate: "2025-12-31",
    coverageAreas: ["Manchester", "Clarendon", "St. Elizabeth", "St. Ann"],
    eligibilityCriteria: ["Rural residence", "No piped water access", "Proof of land ownership or lease"],
    deliveryRate: 85,
  },
  {
    id: "prog-school-feeding",
    name: "National School Feeding Programme",
    code: "NSFP",
    category: "in-kind",
    status: "active",
    description: "Provides nutritious meals to students in primary and secondary schools across Jamaica.",
    ministry: "Ministry of Education and Youth",
    budget: 2800000000,
    disbursed: 2400000000,
    beneficiaries: 290000,
    targetBeneficiaries: 310000,
    applicationsPending: 450,
    applicationsApproved: 6800,
    applicationsRejected: 120,
    weight: 14,
    startDate: "2005-09-01",
    endDate: null,
    coverageAreas: ["Islandwide"],
    eligibilityCriteria: ["Enrolled in participating school", "Parent/guardian consent"],
    deliveryRate: 93,
  },
  {
    id: "prog-disaster-relief",
    name: "Disaster Relief Fund",
    code: "DRF",
    category: "emergency",
    status: "active",
    description: "Emergency financial assistance for individuals and families affected by natural disasters.",
    ministry: "Office of Disaster Preparedness and Emergency Management",
    budget: 500000000,
    disbursed: 180000000,
    beneficiaries: 4200,
    targetBeneficiaries: 10000,
    applicationsPending: 320,
    applicationsApproved: 1800,
    applicationsRejected: 280,
    weight: 10,
    startDate: "2010-01-01",
    endDate: null,
    coverageAreas: ["Islandwide - Disaster affected areas"],
    eligibilityCriteria: ["Affected by declared disaster", "Resident of affected area", "Loss assessment verified"],
    deliveryRate: 88,
  },
  {
    id: "prog-youth-employ",
    name: "Youth Employment Initiative",
    code: "YEI",
    category: "cash-transfer",
    status: "pilot",
    description: "Job training and employment subsidy program for unemployed youth aged 18-30.",
    ministry: "Ministry of Labour and Social Security",
    budget: 800000000,
    disbursed: 420000000,
    beneficiaries: 5600,
    targetBeneficiaries: 15000,
    applicationsPending: 2100,
    applicationsApproved: 3200,
    applicationsRejected: 890,
    weight: 14,
    startDate: "2023-01-01",
    endDate: "2025-12-31",
    coverageAreas: ["Kingston", "St. Andrew", "St. Catherine"],
    eligibilityCriteria: ["Age 18-30", "Currently unemployed", "Secondary education completed"],
    deliveryRate: 72,
  },
  {
    id: "prog-senior-grant",
    name: "Senior Citizens Grant",
    code: "SCG",
    category: "cash-transfer",
    status: "active",
    description: "Monthly stipend for senior citizens who are not receiving NIS pension or other retirement benefits.",
    ministry: "Ministry of Labour and Social Security",
    budget: 1500000000,
    disbursed: 1350000000,
    beneficiaries: 28000,
    targetBeneficiaries: 35000,
    applicationsPending: 1800,
    applicationsApproved: 4500,
    applicationsRejected: 950,
    weight: 12,
    startDate: "2008-04-01",
    endDate: null,
    coverageAreas: ["Islandwide"],
    eligibilityCriteria: ["Age 65+", "No NIS pension", "Income below threshold"],
    deliveryRate: 97,
  },
  {
    id: "prog-agri-support",
    name: "Small Farmer Agricultural Support",
    code: "SFAS",
    category: "in-kind",
    status: "suspended",
    description: "Provides seeds, fertilizers, and equipment to small-scale farmers to improve crop yields.",
    ministry: "Ministry of Agriculture and Fisheries",
    budget: 350000000,
    disbursed: 280000000,
    beneficiaries: 6200,
    targetBeneficiaries: 10000,
    applicationsPending: 0,
    applicationsApproved: 2800,
    applicationsRejected: 420,
    weight: 10,
    startDate: "2017-03-01",
    endDate: "2024-03-31",
    coverageAreas: ["St. Elizabeth", "Manchester", "Clarendon", "St. Ann", "Portland"],
    eligibilityCriteria: ["Registered small farmer", "Land under 5 acres", "Active cultivation"],
    deliveryRate: 82,
  },
]

export const mockApplications: Application[] = [
  {
    id: "app-001",
    applicantId: "872-991",
    applicantName: "Alexander J. Thompson",
    programId: "prog-path",
    programName: "PATH",
    status: "approved",
    submittedDate: "2024-01-05",
    lastUpdated: "2024-01-18",
    priority: "medium",
    assignedOfficer: "Sarah Mitchell",
    division: "craighead",
    community: "craighead-proper",
    requestedAmount: 18000,
    approvedAmount: 18000,
    notes: ["All documents verified", "Income assessment completed"],
    documents: [
      { name: "Income Certificate", status: "verified" },
      { name: "ID Card", status: "verified" },
      { name: "Utility Bill", status: "verified" },
    ],
  },
  {
    id: "app-002",
    applicantId: "901-224",
    applicantName: "Marcus A. Sterling",
    programId: "prog-housing",
    programName: "Social Housing Programme",
    status: "under-review",
    submittedDate: "2024-01-10",
    lastUpdated: "2024-01-20",
    priority: "high",
    assignedOfficer: "David Chen",
    division: "craighead",
    community: "bigwoods",
    requestedAmount: 2500000,
    approvedAmount: null,
    notes: ["Site visit scheduled for Jan 25", "Income verification pending"],
    documents: [
      { name: "Income Certificate", status: "pending" },
      { name: "ID Card", status: "verified" },
      { name: "Land Title", status: "verified" },
    ],
  },
  {
    id: "app-003",
    applicantId: "552-301",
    applicantName: "Sarah L. Richards",
    programId: "prog-edu-grant",
    programName: "Education Grant Programme",
    status: "approved",
    submittedDate: "2023-12-15",
    lastUpdated: "2024-01-02",
    priority: "medium",
    assignedOfficer: "Michelle Brown",
    division: "craighead",
    community: "golden-run",
    requestedAmount: 150000,
    approvedAmount: 150000,
    notes: ["Academic records excellent", "Full grant approved"],
    documents: [
      { name: "Enrollment Letter", status: "verified" },
      { name: "Transcript", status: "verified" },
      { name: "Parent Income Statement", status: "verified" },
    ],
  },
  {
    id: "app-004",
    applicantId: "412-885",
    applicantName: "David O. Wellington",
    programId: "prog-senior-grant",
    programName: "Senior Citizens Grant",
    status: "pending",
    submittedDate: "2024-01-15",
    lastUpdated: "2024-01-15",
    priority: "urgent",
    assignedOfficer: null,
    division: "craighead",
    community: "norway",
    requestedAmount: 6500,
    approvedAmount: null,
    notes: ["Awaiting officer assignment"],
    documents: [
      { name: "Birth Certificate", status: "verified" },
      { name: "ID Card", status: "pending" },
      { name: "Income Declaration", status: "pending" },
    ],
  },
  {
    id: "app-005",
    applicantId: "623-117",
    applicantName: "Keisha M. Brown",
    programId: "prog-healthcare",
    programName: "NHF Drug Subsidy Programme",
    status: "approved",
    submittedDate: "2023-11-20",
    lastUpdated: "2023-12-05",
    priority: "low",
    assignedOfficer: "Robert Williams",
    division: "craighead",
    community: "pike-proper",
    requestedAmount: null,
    approvedAmount: null,
    notes: ["Card issued", "Annual renewal due Dec 2024"],
    documents: [
      { name: "Medical Certificate", status: "verified" },
      { name: "NHF Application", status: "verified" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-006",
    applicantId: "734-228",
    applicantName: "Michael R. Grant",
    programId: "prog-youth-employ",
    programName: "Youth Employment Initiative",
    status: "waitlisted",
    submittedDate: "2024-01-08",
    lastUpdated: "2024-01-19",
    priority: "medium",
    assignedOfficer: "Patricia Clarke",
    division: "craighead",
    community: "coleyville-proper",
    requestedAmount: 45000,
    approvedAmount: null,
    notes: ["Qualified but program capacity reached", "Position: #23 on waitlist"],
    documents: [
      { name: "CV", status: "verified" },
      { name: "Academic Certificate", status: "verified" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-007",
    applicantId: "845-339",
    applicantName: "Patricia A. Williams",
    programId: "prog-water-tank",
    programName: "Rural Water Tank Programme",
    status: "approved",
    submittedDate: "2023-10-05",
    lastUpdated: "2023-11-15",
    priority: "high",
    assignedOfficer: "James Thompson",
    division: "walderston",
    community: "chudleigh-proper",
    requestedAmount: 85000,
    approvedAmount: 85000,
    notes: ["Tank delivered", "Installation completed"],
    documents: [
      { name: "Property Deed", status: "verified" },
      { name: "Water Assessment", status: "verified" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-008",
    applicantId: "956-440",
    applicantName: "Dwayne K. Mitchell",
    programId: "prog-agri-support",
    programName: "Small Farmer Agricultural Support",
    status: "rejected",
    submittedDate: "2023-09-20",
    lastUpdated: "2023-10-10",
    priority: "medium",
    assignedOfficer: "Michelle Brown",
    division: "walderston",
    community: "top-hill-proper",
    requestedAmount: 120000,
    approvedAmount: null,
    notes: ["Land size exceeds program limit", "Referred to commercial farming program"],
    documents: [
      { name: "Farm Registration", status: "verified" },
      { name: "Land Survey", status: "rejected" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-009",
    applicantId: "167-551",
    applicantName: "Shanice R. Campbell",
    programId: "prog-path",
    programName: "PATH",
    status: "approved",
    submittedDate: "2023-08-15",
    lastUpdated: "2023-09-01",
    priority: "medium",
    assignedOfficer: "Sarah Mitchell",
    division: "walderston",
    community: "walderston-proper",
    requestedAmount: 24000,
    approvedAmount: 24000,
    notes: ["Renewal approved", "Next review: Aug 2024"],
    documents: [
      { name: "Income Certificate", status: "verified" },
      { name: "School Enrollment", status: "verified" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-010",
    applicantId: "278-662",
    applicantName: "Garfield L. Henry",
    programId: "prog-disaster-relief",
    programName: "Disaster Relief Fund",
    status: "under-review",
    submittedDate: "2024-01-12",
    lastUpdated: "2024-01-18",
    priority: "urgent",
    assignedOfficer: "David Chen",
    division: "walderston",
    community: "mile-gully",
    requestedAmount: 350000,
    approvedAmount: null,
    notes: ["Hurricane damage assessment in progress", "Expedited processing requested"],
    documents: [
      { name: "Damage Photos", status: "verified" },
      { name: "Police Report", status: "pending" },
      { name: "Property Document", status: "verified" },
    ],
  },
  {
    id: "app-011",
    applicantId: "389-773",
    applicantName: "Nadine E. Thomas",
    programId: "prog-edu-grant",
    programName: "Education Grant Programme",
    status: "pending",
    submittedDate: "2024-01-14",
    lastUpdated: "2024-01-14",
    priority: "low",
    assignedOfficer: null,
    division: "walderston",
    community: "chantilly-proper",
    requestedAmount: 200000,
    approvedAmount: null,
    notes: ["New application received"],
    documents: [
      { name: "University Acceptance", status: "pending" },
      { name: "Income Statement", status: "pending" },
      { name: "ID Card", status: "verified" },
    ],
  },
  {
    id: "app-012",
    applicantId: "490-884",
    applicantName: "Carlton W. James",
    programId: "prog-school-feeding",
    programName: "National School Feeding Programme",
    status: "approved",
    submittedDate: "2023-09-01",
    lastUpdated: "2023-09-10",
    priority: "low",
    assignedOfficer: "Robert Williams",
    division: "christiana",
    community: "christiana-proper",
    requestedAmount: null,
    approvedAmount: null,
    notes: ["Children enrolled for school year 2023-24"],
    documents: [
      { name: "Parent Consent Form", status: "verified" },
      { name: "School Enrollment", status: "verified" },
    ],
  },
  {
    id: "app-013",
    applicantId: "501-995",
    applicantName: "Marcia D. Anderson",
    programId: "prog-housing",
    programName: "Social Housing Programme",
    status: "under-review",
    submittedDate: "2024-01-03",
    lastUpdated: "2024-01-17",
    priority: "high",
    assignedOfficer: "James Thompson",
    division: "christiana",
    community: "spring-ground-proper",
    requestedAmount: 1800000,
    approvedAmount: null,
    notes: ["Financial assessment completed", "Awaiting final committee review"],
    documents: [
      { name: "Income Verification", status: "verified" },
      { name: "Family Composition", status: "verified" },
      { name: "Current Housing Proof", status: "verified" },
    ],
  },
  {
    id: "app-014",
    applicantId: "612-106",
    applicantName: "Damion P. Clarke",
    programId: "prog-youth-employ",
    programName: "Youth Employment Initiative",
    status: "approved",
    submittedDate: "2023-11-01",
    lastUpdated: "2023-12-01",
    priority: "medium",
    assignedOfficer: "Patricia Clarke",
    division: "christiana",
    community: "hibernia-proper",
    requestedAmount: 45000,
    approvedAmount: 45000,
    notes: ["Placed at local business", "6-month internship started Jan 2024"],
    documents: [
      { name: "CV", status: "verified" },
      { name: "Academic Certificate", status: "verified" },
      { name: "Reference Letters", status: "verified" },
    ],
  },
  {
    id: "app-015",
    applicantId: "723-217",
    applicantName: "Tanya S. Morgan",
    programId: "prog-healthcare",
    programName: "NHF Drug Subsidy Programme",
    status: "pending",
    submittedDate: "2024-01-16",
    lastUpdated: "2024-01-16",
    priority: "high",
    assignedOfficer: null,
    division: "christiana",
    community: "devon-proper",
    requestedAmount: null,
    approvedAmount: null,
    notes: ["Urgent medical need indicated"],
    documents: [
      { name: "Medical Certificate", status: "pending" },
      { name: "Doctor Referral", status: "pending" },
      { name: "ID Card", status: "verified" },
    ],
  },
]

export interface Person {
  id: string
  name: string
  submissionRatio: { submitted: number; total: number }
  approvalRate: number
  impactScore: number
  // Location
  division: string
  community: string
  // Demographics
  age: number
  gender: "male" | "female"
  occupation: string
  maritalStatus: string
}

export const mockPeople: Person[] = [
  // Craighead Division
  {
    id: "872-991",
    name: "Alexander J. Thompson",
    submissionRatio: { submitted: 9, total: 10 },
    approvalRate: 92,
    impactScore: 88,
    division: "craighead",
    community: "craighead-proper",
    age: 45,
    gender: "male",
    occupation: "public-servant",
    maritalStatus: "married",
  },
  {
    id: "901-224",
    name: "Marcus A. Sterling",
    submissionRatio: { submitted: 7, total: 10 },
    approvalRate: 64,
    impactScore: 71,
    division: "craighead",
    community: "bigwoods",
    age: 32,
    gender: "male",
    occupation: "private-sector",
    maritalStatus: "single",
  },
  {
    id: "552-301",
    name: "Sarah L. Richards",
    submissionRatio: { submitted: 10, total: 10 },
    approvalRate: 97,
    impactScore: 95,
    division: "craighead",
    community: "golden-run",
    age: 28,
    gender: "female",
    occupation: "self-employed",
    maritalStatus: "single",
  },
  {
    id: "412-885",
    name: "David O. Wellington",
    submissionRatio: { submitted: 4, total: 10 },
    approvalRate: 32,
    impactScore: 28,
    division: "craighead",
    community: "norway",
    age: 55,
    gender: "male",
    occupation: "unemployed",
    maritalStatus: "divorced",
  },
  {
    id: "623-117",
    name: "Keisha M. Brown",
    submissionRatio: { submitted: 8, total: 10 },
    approvalRate: 85,
    impactScore: 82,
    division: "craighead",
    community: "pike-proper",
    age: 38,
    gender: "female",
    occupation: "public-servant",
    maritalStatus: "married",
  },
  {
    id: "734-228",
    name: "Michael R. Grant",
    submissionRatio: { submitted: 6, total: 10 },
    approvalRate: 58,
    impactScore: 61,
    division: "craighead",
    community: "coleyville-proper",
    age: 24,
    gender: "male",
    occupation: "student",
    maritalStatus: "single",
  },
  // Walderston Division
  {
    id: "845-339",
    name: "Patricia A. Williams",
    submissionRatio: { submitted: 9, total: 10 },
    approvalRate: 89,
    impactScore: 91,
    division: "walderston",
    community: "chudleigh-proper",
    age: 52,
    gender: "female",
    occupation: "private-sector",
    maritalStatus: "widowed",
  },
  {
    id: "956-440",
    name: "Dwayne K. Mitchell",
    submissionRatio: { submitted: 5, total: 10 },
    approvalRate: 45,
    impactScore: 48,
    division: "walderston",
    community: "top-hill-proper",
    age: 41,
    gender: "male",
    occupation: "self-employed",
    maritalStatus: "married",
  },
  {
    id: "167-551",
    name: "Shanice R. Campbell",
    submissionRatio: { submitted: 10, total: 10 },
    approvalRate: 95,
    impactScore: 93,
    division: "walderston",
    community: "walderston-proper",
    age: 35,
    gender: "female",
    occupation: "public-servant",
    maritalStatus: "married",
  },
  {
    id: "278-662",
    name: "Garfield L. Henry",
    submissionRatio: { submitted: 3, total: 10 },
    approvalRate: 25,
    impactScore: 22,
    division: "walderston",
    community: "mile-gully",
    age: 67,
    gender: "male",
    occupation: "unemployed",
    maritalStatus: "married",
  },
  {
    id: "389-773",
    name: "Nadine E. Thomas",
    submissionRatio: { submitted: 7, total: 10 },
    approvalRate: 72,
    impactScore: 69,
    division: "walderston",
    community: "chantilly-proper",
    age: 29,
    gender: "female",
    occupation: "private-sector",
    maritalStatus: "single",
  },
  // Christiana Division
  {
    id: "490-884",
    name: "Carlton W. James",
    submissionRatio: { submitted: 8, total: 10 },
    approvalRate: 81,
    impactScore: 79,
    division: "christiana",
    community: "christiana-proper",
    age: 48,
    gender: "male",
    occupation: "self-employed",
    maritalStatus: "married",
  },
  {
    id: "501-995",
    name: "Marcia D. Anderson",
    submissionRatio: { submitted: 9, total: 10 },
    approvalRate: 88,
    impactScore: 86,
    division: "christiana",
    community: "spring-ground-proper",
    age: 33,
    gender: "female",
    occupation: "public-servant",
    maritalStatus: "single",
  },
  {
    id: "612-106",
    name: "Damion P. Clarke",
    submissionRatio: { submitted: 6, total: 10 },
    approvalRate: 55,
    impactScore: 52,
    division: "christiana",
    community: "hibernia-proper",
    age: 26,
    gender: "male",
    occupation: "student",
    maritalStatus: "single",
  },
  {
    id: "723-217",
    name: "Tanya S. Morgan",
    submissionRatio: { submitted: 10, total: 10 },
    approvalRate: 99,
    impactScore: 97,
    division: "christiana",
    community: "devon-proper",
    age: 44,
    gender: "female",
    occupation: "private-sector",
    maritalStatus: "married",
  },
  {
    id: "834-328",
    name: "Winston H. Barrett",
    submissionRatio: { submitted: 4, total: 10 },
    approvalRate: 38,
    impactScore: 35,
    division: "christiana",
    community: "halifax",
    age: 59,
    gender: "male",
    occupation: "unemployed",
    maritalStatus: "divorced",
  },
  {
    id: "945-439",
    name: "Simone K. Lewis",
    submissionRatio: { submitted: 7, total: 10 },
    approvalRate: 68,
    impactScore: 65,
    division: "christiana",
    community: "brontie",
    age: 31,
    gender: "female",
    occupation: "self-employed",
    maritalStatus: "single",
  },
]
